name: rawr
description: Flutter project that implements the idea of a group card that uses [appwrite](https://appwrite.io/) as a backend service and [GetX]((https://pub.dev/packages/get)) as a state management solution.


version: 1.0.0+1


environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.2

  # GetX
  get: ^4.6.1

  # TODO: Change package name and remove this package 
  change_app_package_name: ^1.0.0
  appwrite: ^4.0.2
  get_storage: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  